### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by MisterSingh** [Strategizer/app#11]
# Requirement for Header
Create a nav bar header using [AppBar of material UI](https://material-ui.com/components/app-bar/#app-bar).
<ul>
<li> Left side: App logo (not must but go crazy)</li>
<li> Left side: App name</li>
<li> Right side: About page</li>
<li> Right side: Contributors</li>
</ul>

**Comment by mphelps1978** [comment]
Is there  a wireframe for the app already? I wouldn't mind taking this one, however I can't find anything regarding the UX Design of this, so I wouldn't know where to start as far as color theming, if there's already a logo, etc..

**Comment by quelingeeson** [comment]
Hi @mphelps1978 ,

The basic idea of the layout is demonstrated in  [Figma](https://www.figma.com/proto/LOZLXXVxLznj9GBYdBW2vy/App?node-id=7%3A43&scaling=min-zoom). But this is not set and done. Any changes and suggestions are welcome. As far as the color theme, the primary color is indigo and the secondary color is green. You can refer to this [Material Theme Playground](https://material-ui.com/customization/color/#playground). As of now, there is no logo, but you can use any free static logo so that we can replace it later.

If you are up for it, we can assign this issue to you.

**Comment by mphelps1978** [comment]
I'll take it. PR by tomorrow-ish...

**Comment by mphelps1978** [comment]
I'm going to move the hamburger menu to the other side. Where it's sitting now, will look real odd next to a logo..
